name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: "16"

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user to "jucian0"
      shell: bash
      run: git config user.email "juciano@outlook.comm.br" && git config user.name "jucian0"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org

    - name: yarn install
      shell: bash
      run: yarn install --immutable --immutable-cache
