name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: "16"

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user to "🤖"
      shell: bash
      run: git config --global user.email 'github-actions[bot]@users.noreply.github.com' && git config --global user.name 'github-actions[bot]'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org

    - name: Setup pnpm 7
      uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Install dependencies
      shell: bash
      run: pnpm install
