name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
